development:
  adapter: postgresql
  database: rocioart_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: rocioart_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rocioart_production
  pool: 5
  timeout: 5000