# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5849cb4fbc8b74e121f7f2da386866feafaf6abf375c0ff7007050b73a3c897388ffa1289f4ad8d881032b68e9a7c206ecaf48229c4da4f9dfdfbce45a52b3f7

test:
  secret_key_base: 9c734f89ff3ed79de920f9670eccf919807b6779e657a654c04c13571c2f1d60dde1d98203e42233b4078ea0f3548c47458630dd3ba8b55d73facaa037e14727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
